# ============================================================
#  Telebot Creator (TPY) commands for tbc-pdf-api
#  Each "# ===== command: /xxx =====" block is a separate TBC command.
#  Replace API and KEY in each one (or keep them in one place you like).
#  Flow: POST /make -> returns a signed link -> bot.sendDocument(link)
#  Telegram downloads the PDF itself, so no file handling in TBC.
# ============================================================


# ===== command: /invoice =====
API = "https://YOUR-PROJECT.vercel.app"
KEY = "YOUR_API_KEY"

try:
    r = HTTP.post(API + "/make", headers={"x-api-key": KEY}, json={
        "template": "invoice",
        "filename": "invoice-1001",
        "data": {
            "brand": "Acme Studio",
            "tagline": "Web apps, bots & APIs",
            "accent": "#4f46e5",
            "invoiceNo": "INV-1001",
            "date": "07 Oct 2026",
            "due": "14 Oct 2026",
            "status": "UNPAID",
            "from": ["Acme Studio", "Jamshedpur, Jharkhand"],
            "to": ["Client Name", "Client address"],
            "currency": "Rs.",
            "taxLabel": "GST",
            "taxPct": 18,
            "items": [
                {"desc": "Telegram bot development", "qty": 1, "price": 12000},
                {"desc": "API integration", "qty": 2, "price": 1500}
            ],
            "notes": "Payment due within 7 days.",
            "payment": ["UPI: yourname@upi"]
        }
    })
    j = r.json()
    if j.get("ok"):
        bot.sendDocument(document=j["url"], caption="Your invoice is ready")
    else:
        bot.sendMessage("PDF failed: " + str(j.get("error")))
except Exception as e:
    bot.sendMessage("PDF service error: " + str(e))


# ===== command: /cert =====
# Usage: /cert Rahul Kumar     (the name comes from params)
API = "https://YOUR-PROJECT.vercel.app"
KEY = "YOUR_API_KEY"

name = params if params else "Your Name"

try:
    r = HTTP.post(API + "/make", headers={"x-api-key": KEY}, json={
        "template": "certificate",
        "filename": "certificate",
        "data": {
            "title": "Certificate of Achievement",
            "name": name,
            "body": "in recognition of outstanding performance and dedication.",
            "issuer": "Acme Academy",
            "date": "07 October 2026",
            "signer": "A. Mehta",
            "signerTitle": "Program Director",
            "id": "CERT-" + str(u),
            "accent": "#b45309"
        }
    })
    j = r.json()
    if j.get("ok"):
        bot.sendDocument(document=j["url"], caption="Congratulations, " + name + "!")
    else:
        bot.sendMessage("PDF failed: " + str(j.get("error")))
except Exception as e:
    bot.sendMessage("PDF service error: " + str(e))


# ===== command: /report =====
# Turn any dict of results (e.g. from a lookup API) into a clean PDF report.
API = "https://YOUR-PROJECT.vercel.app"
KEY = "YOUR_API_KEY"

# Replace this with the data your bot already has, e.g. data = HTTP.get(...).json()
rows = {
    "Name": "Sample Name",
    "ID": "123456",
    "Status": "Active",
    "Address": "Some long address that will wrap nicely across lines in the PDF"
}

try:
    r = HTTP.post(API + "/make", headers={"x-api-key": KEY}, json={
        "template": "report",
        "filename": "report",
        "data": {
            "title": "Lookup Report",
            "subtitle": "Generated by my bot",
            "accent": "#0f766e",
            "rows": rows
        }
    })
    j = r.json()
    if j.get("ok"):
        bot.sendDocument(document=j["url"], caption="Your report")
    else:
        bot.sendMessage("PDF failed: " + str(j.get("error")))
except Exception as e:
    bot.sendMessage("PDF service error: " + str(e))


# ===== command: /custom =====
# Fully custom design: send a "doc" instead of a template (see README "Design anything").
# Coordinates are in points from the TOP-LEFT. A4 = 595 x 842.
API = "https://YOUR-PROJECT.vercel.app"
KEY = "YOUR_API_KEY"

try:
    r = HTTP.post(API + "/make", headers={"x-api-key": KEY}, json={
        "filename": "custom",
        "doc": {
            "size": "A5",
            "pages": [{
                "bg": "#0f172a",
                "els": [
                    {"t": "rect", "x": 24, "y": 24, "w": 372, "h": 120, "r": 16, "fill": "#38bdf8"},
                    {"t": "text", "x": 24, "y": 62, "w": 372, "text": "Hello from my bot", "size": 26, "font": "sans-bold", "color": "#0f172a", "align": "center"},
                    {"t": "text", "x": 40, "y": 180, "w": 340, "text": "Any layout you can describe with rect, circle, line, text and image elements.", "size": 13, "color": "#e2e8f0", "lh": 1.5},
                    {"t": "circle", "x": 210, "y": 400, "r": 50, "fill": "#fbbf24"}
                ]
            }]
        }
    })
    j = r.json()
    if j.get("ok"):
        bot.sendDocument(document=j["url"])
    else:
        bot.sendMessage("PDF failed: " + str(j.get("error")))
except Exception as e:
    bot.sendMessage("PDF service error: " + str(e))


# ===== command: /generate =====
# The RC flow: /generate JH05CK2458 -> vehicle API lookup -> PDF service -> signed link.
# Telegram downloads the PDF from the link itself.
API = "https://YOUR-PROJECT.vercel.app"
KEY = "YOUR_API_KEY"

reg = (params if params else "").strip().replace(" ", "").upper()
if not reg:
    bot.sendMessage("Usage: /generate JH05CK2458")
else:
    try:
        v = HTTP.get("https://vehicle-api-tau.vercel.app/api/vehicle?vnum=" + reg).json()
    except Exception as e:
        bot.sendMessage("Vehicle lookup failed: " + str(e))
        v = None
    if v is not None and v.get("registration_number"):
        try:
            r = HTTP.post(API + "/make", headers={"x-api-key": KEY}, json={
                "template": "rc",
                "filename": "RC_" + reg,
                "data": v
            })
            j = r.json()
            if j.get("ok"):
                bot.sendDocument(document=j["url"], caption="Registration Certificate for " + reg)
            else:
                bot.sendMessage("PDF failed: " + str(j.get("error")))
        except Exception as e:
            bot.sendMessage("PDF service error: " + str(e))
    elif v is not None:
        bot.sendMessage("No RC record found for " + reg + ". Check the registration number.")
